---
windows: false
internal structure: true
media viewer: eog
output directory: watch
database directory: db
database location: database.db
new files: sort
deleted directory: deleted
potential duplicates: dups
